### ISSUE TITLE
Can´t be build...

### ISSUE THREAD

**Issue by Keksstar** [peschuster/casparcg-hyperdeck#10]
Any ideas on that error?:

casparcg-hyperdeck-master\libs\casparcg-connection>npm run build:main
npm ERR! missing script: build:main
npm ERR!
npm ERR! Did you mean one of these?
npm ERR! build
npm ERR! build-win32

**Comment by peschuster** [comment]
I just tested a fresh checkout and added `git submodule init` to the build instructions.
It brings a warning about highlight.js 9 being expired, but should work.
