### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by dman776** [peschuster/casparcg-hyperdeck#2]
Can you clarify the build instructions?
I have cloned the repo with --recursive to get the libs (submodules)
i have gone into both libs and npm install

when i npm run build-win32 on the main repo, i get errors like:

node_modules/@types/node/http2.d.ts(724,80): error TS1110: Type expected.
node_modules/@types/node/http2.d.ts(725,69): error TS1110: Type expected.
node_modules/@types/node/http2.d.ts(726,87): error TS1110: Type expected.
node_modules/@types/node/http2.d.ts(727,89): error TS1110: Type expected.
node_modules/@types/node/http2.d.ts(728,90): error TS1110: Type expected.
node_modules/@types/node/https.d.ts(7,51): error TS1005: ';' expected.
node_modules/@types/node/https.d.ts(9,47): error TS1005: ';' expected.
node_modules/@types/node/https.d.ts(10,37): error TS1005: ',' expected.
node_modules/@types/node/https.d.ts(11,28): error TS1005: ',' expected.
node_modules/@types/node/https.d.ts(28,43): error TS1110: Type expected.
node_modules/@types/node/https.d.ts(29,60): error TS1110: Type expected.
node_modules/@types/node/https.d.ts(35,35): error TS1110: Type expected.
node_modules/@types/node/index.d.ts(78,5): error TS1131: Property or signatu
node_modules/@types/node/index.d.ts(78,14): error TS1005: ';' expected.
node_modules/@types/node/index.d.ts(79,14): error TS1005: ';' expected.

**Comment by peschuster** [comment]
I just updated the readme and successfully build it in a fresh checkout following these instructions. Does that solve your issue?

**Comment by dman776** [comment]
Thanks.   Looks like the --recursive checkout has permissions issues.
```


git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:peschuster/node-osc.git' into submodule path '/Users/darrylquinn/github/casparcg-hyperdeck/libs/node-osc' failed
Failed to clone 'libs/node-osc'. Retry scheduled
Cloning into '/Users/darrylquinn/github/casparcg-hyperdeck/libs/node-osc'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:peschuster/node-osc.git' into submodule path '/Users/darrylquinn/github/casparcg-hyperdeck/libs/node-osc' failed
Failed to clone 'libs/node-osc' a second time, aborting
Cloning into '/Users/darrylquinn/github/casparcg-hyperdeck/libs/casparcg-connection'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:peschuster/casparcg-connection.git' into submodule path '/Users/darrylquinn/github/casparcg-hyperdeck/libs/casparcg-connection' failed
Failed to clone 'libs/casparcg-connection' a second time, aborting

```

**Comment by peschuster** [comment]
Ok, just pushed another fix changing the urls to https. That should fix the permission issue.

**Comment by dman776** [comment]
BTW...
node --version = 13.6.0
npm --version = 6.13.4

the git: to https: protocol change fixed that issue.

moving further.

1. git clone --recursive ....
2. cd libs/node-osc
3. npm install
4. cd ../casparcg-connection
5. npm install
6. cd ../..
7. edit tsconfig.json to uncomment 'files'
8. npm install pkg
9. npm run build-win32 

tsconfig.json has an invalid /* */ comment around the files section.   I uncommented it.  (was this correct?)
next, had to "npm install pkg"
next, in project root, i ran "npm run build-win32", received this error...

> pkg@4.4.2
**> Error! Input file does not exist
  C:\Users\Darryl Quinn\github\casparcg-hyperdeck\dist\app_clips.js**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! hyperdeck-proxy@1.0.0 build-win32: `npm run clean && npm run build && pkg -t no
lipserver.json bin /Y && pkg -t node8-win dist/app_template.js -o bin/CasparHyperdeckTem
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the hyperdeck-proxy@1.0.0 build-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging out
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by peschuster** [comment]
Updated documentation and tested order of commands using github actions
