### ISSUE TITLE
Example CSV file

### ISSUE THREAD

**Issue by rf152** [peschuster/casparcg-hyperdeck#5]
Is there any possibility of an example CSV file for the template server? I did look, but I couldn't find one.

**Comment by peschuster** [comment]
There is no example file in the repository.

The file should have an utf-8 encoding and needs to use `;` as a separator.
The first column must contain the name of the template (as you would use in Caspar CG commands).
Data in the following columns is passed to the template as parameters (one parameter per column).
The first row is assumed to contain column headers and therefore discarded.
